
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aeaya
 */
public class Equipos extends javax.swing.JFrame {
ConexionDB conSQL = new ConexionDB();

    /**
     * Creates new form Equipos
     */
    public Equipos() {
        initComponents();
         a = new Atributos();
         
         TablaMostrar();
         TablaBuscar();
         TablaEliminar();
         TablaModificar();
         
         
         configurarSeleccionDeFilaEliminar();
         configurarSeleccionDeFilaModificar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jTextField6 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(170, 120, 70, 50);

        jLabel2.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE DEL EQUIPO");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(40, 190, 200, 50);

        jLabel3.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(90, 260, 120, 50);
        jPanel3.add(jTextField1);
        jTextField1.setBounds(240, 120, 150, 50);
        jPanel3.add(jTextField2);
        jTextField2.setBounds(240, 190, 150, 50);

        jButton1.setText("Guardar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(120, 490, 150, 50);

        jLabel4.setFont(new java.awt.Font("SimSun-ExtB", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NUEVOS EQUIPOS");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 30, 350, 70);

        jButton8.setText("Limpiar");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(310, 490, 140, 50);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(240, 260, 350, 160);

        jTabbedPane1.addTab("Nuevo Equipo", jPanel3);

        jPanel4.setBackground(new java.awt.Color(51, 153, 0));
        jPanel4.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_EQUIPO", "NOMBRE", "DESCRIPCION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(62, 72, 640, 430);

        jTabbedPane1.addTab("Mostrar", jPanel4);

        jPanel5.setBackground(new java.awt.Color(51, 153, 0));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel5.setText("DAME UN ID");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(40, 30, 170, 40);

        jLabel6.setText("NOMBRE");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(537, 120, 80, 40);

        jLabel7.setText("DESCRIPCION");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(540, 220, 110, 40);
        jPanel5.add(jTextField5);
        jTextField5.setBounds(170, 30, 140, 40);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_EQUIPO", "NOMBRE", "DESCRIPCION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable4);

        jPanel5.add(jScrollPane5);
        jScrollPane5.setBounds(40, 100, 452, 402);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        jPanel5.add(jScrollPane6);
        jScrollPane6.setBounds(550, 270, 234, 86);
        jPanel5.add(jTextField6);
        jTextField6.setBounds(630, 110, 160, 50);

        jButton11.setText("BUSCAR");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton11MousePressed(evt);
            }
        });
        jPanel5.add(jButton11);
        jButton11.setBounds(350, 40, 100, 30);

        jButton12.setText("MODIFICAR");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton12MousePressed(evt);
            }
        });
        jPanel5.add(jButton12);
        jButton12.setBounds(561, 413, 130, 50);

        jTabbedPane1.addTab("Modificar", jPanel5);

        jPanel6.setBackground(new java.awt.Color(51, 153, 0));
        jPanel6.setLayout(null);

        jLabel9.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DAME UN ID");
        jPanel6.add(jLabel9);
        jLabel9.setBounds(70, 40, 180, 50);
        jPanel6.add(jTextField4);
        jTextField4.setBounds(200, 40, 150, 40);

        jButton10.setText("BUSCAR");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
        });
        jPanel6.add(jButton10);
        jButton10.setBounds(380, 40, 100, 40);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_EQUIPO", "NOMBRE", "DESCRIPCION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable3);

        jPanel6.add(jScrollPane4);
        jScrollPane4.setBounds(70, 110, 452, 402);

        jTabbedPane1.addTab("Eliminar", jPanel6);

        jPanel7.setBackground(new java.awt.Color(51, 153, 0));
        jPanel7.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_EQUIPO", "NOMBRE", "DESCRIPCION"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jPanel7.add(jScrollPane3);
        jScrollPane3.setBounds(60, 120, 610, 402);

        jLabel8.setFont(new java.awt.Font("SimSun", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("DAME UN ID:");
        jPanel7.add(jLabel8);
        jLabel8.setBounds(50, 50, 160, 40);
        jPanel7.add(jTextField3);
        jTextField3.setBounds(180, 40, 190, 50);

        jButton9.setText("BUSCA");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9MousePressed(evt);
            }
        });
        jPanel7.add(jButton9);
        jButton9.setBounds(400, 50, 110, 40);

        jTabbedPane1.addTab("Buscar", jPanel7);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(170, 30, 830, 660);

        jButton2.setText("Usuarios");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 170, 120, 40);

        jButton3.setText("Equipos");
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 240, 120, 40);

        jButton4.setText("Partida");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 310, 120, 40);

        jButton5.setText("Equipamiento");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(20, 380, 120, 40);

        jButton7.setText("SALIR");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(20, 570, 120, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1010, 690);

        setSize(new java.awt.Dimension(1020, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        Usuarios usuframe = new Usuarios();
        usuframe.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextArea1.setText(null);
    }//GEN-LAST:event_jButton8MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:

        boolean error = false;

        try {
            int nuevoIdEquipo = Integer.parseInt(jTextField1.getText().trim());

            // Verificar si el ID de usuario ya existe
            if (idEquipoExiste(nuevoIdEquipo)) {
                JOptionPane.showMessageDialog(null, "Error: El ID de Equipo ya existe en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            a.setIdEquipo(nuevoIdEquipo);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Ingresa un valor numérico válido para el ID de Equipo.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        }

        String nombre = jTextField2.getText().trim();
        if (!nombre.matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(null, "Error: El nombre solo puede contener letras y espacios.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        } else {
            a.setNombreEquipo(nombre);
        }

        a.setDescripcion(jTextArea1.getText().trim());

        try {
            String query = "INSERT INTO equipos(ID_Equipo, Nombre_Equipo, Descripcion) VALUES(?, ?, ?)";
            PreparedStatement pps = conSQL.prepareStatement(query);
            pps.setInt(1, a.getIdEquipo());
            pps.setString(2, a.getNombreEquipo());
            pps.setString(3, a.getDescripcion());

            pps.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar los datos en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (!error) {
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
        }

        TablaEliminar();
            TablaMostrar();
            TablaBuscar();
            TablaModificar();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed
        // TODO add your handling code here:
        
          int idBuscada = 0;  // Inicializar la variable idBuscada fuera del try-catch

try {
    idBuscada = Integer.parseInt(jTextField3.getText());  // Obtener el ID de búsqueda del JTextField
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido.", "Error", JOptionPane.ERROR_MESSAGE);
    return;  // Salir del método si el usuario no ingresó un número válido
}
try {
    String query = "SELECT * FROM equipos WHERE ID_Equipo LIKE ?";
    PreparedStatement pstmt = conSQL.getConectarDB().prepareStatement(query);
    pstmt.setString(1, idBuscada + "%");  // El símbolo '%' permite buscar registros que comiencen con el ID proporcionado
    
    ResultSet result = pstmt.executeQuery();
    
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID_Equipo");
    modelo.addColumn("Nombre");
    modelo.addColumn("Descripcion");
    
    
    
    while (result.next()) {
        Object[] fila = new Object[9];
        fila[0] = result.getString("ID_Equipo");
        fila[1] = result.getString("Nombre_Equipo");
        fila[2] = result.getString("Descripcion");
     
       
        modelo.addRow(fila);
    }
    
    jTable2.setModel(modelo);
    
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error al buscar registros en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
}   
    
    }//GEN-LAST:event_jButton9MousePressed

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        // TODO add your handling code here:
        int idBuscada = 0;
    boolean entradaValida = false;

    do {
         try {
            String input = jTextField4.getText().trim();
            for (char c : input.toCharArray()) {
                if (!Character.isDigit(c)) {
                    throw new NumberFormatException();
                }
            }
            if (input.length() < 5) {
                idBuscada = Integer.parseInt(input);
               
                entradaValida = true;
            } else {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese exactamente 4 dígitos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
            break;
        }
    } while (!entradaValida);

     if (entradaValida) {
        try {
            // Realizar una consulta SQL para obtener los datos del registro en la base de datos
            String query = "SELECT * FROM equipos WHERE ID_Equipo = ?";
            try (PreparedStatement preparedStatement = conSQL.prepareStatement(query)) {
                preparedStatement.setInt(1, idBuscada);
                try (ResultSet result = preparedStatement.executeQuery()) {

                    DefaultTableModel model = (DefaultTableModel) jTable3.getModel();

                    // Limpiar la tabla antes de agregar nuevos datos
                    LimpiarTabla(model);

                    if (result.next()) {
                        // Obtener los datos del resultado
                        int id = result.getInt("ID_Equipo");
                        String nombre = result.getString("Nombre_Equipo");
                        String descripcion = result.getString("Descripcion");
                        

                        // Agregar los datos al DefaultTableModel asociado al JTable
                        model.addRow(new Object[]{id, nombre, descripcion});

                        // Preguntar al usuario si desea eliminar el registro
                        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

                        if (opcion == JOptionPane.YES_OPTION) {
                            // Eliminar el registro de la base de datos
                            eliminarRegistro(id);

                            // No es necesario limpiar y mostrar la tabla aquí ya que se hace después
                        } else {
                            JOptionPane.showMessageDialog(null, "Eliminación cancelada.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontró un registro con el ID especificado.");
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al realizar la consulta en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Limpiar y mostrar la tabla después de la eliminación
            DefaultTableModel modeloTabla = (DefaultTableModel) jTable3.getModel();
            LimpiarTabla(modeloTabla);
            TablaEliminar();
            TablaMostrar();
            TablaBuscar();
            TablaModificar();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese exactamente 4 dígitos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }  
        
        
        
        
    }//GEN-LAST:event_jButton10MousePressed

    private void jButton11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MousePressed
        // TODO add your handling code here:
        
           int idBuscada = 0;
    boolean entradaValida = false;

    do {
         try {
            String input = jTextField5.getText().trim();
            for (char c : input.toCharArray()) {
                if (!Character.isDigit(c)) {
                    throw new NumberFormatException();
                }
            }
            if (input.length() < 5) {
                a.setIdBuscadaEquipo(Integer.parseInt(input));
               
                entradaValida = true;
            } else {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese exactamente 4 dígitos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
            break;
        }
    } while (!entradaValida);

    if (entradaValida) {
        
        try {
            // Realizar una consulta SQL para obtener los datos del registro en la base de datos
            String query = "SELECT * FROM equipos WHERE ID_Equipo = ?";
            PreparedStatement preparedStatement = conSQL.prepareStatement(query);
            preparedStatement.setInt(1, a.getIdBuscadaEquipo());
            ResultSet result = preparedStatement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();

                    // Limpiar la tabla antes de agregar nuevos datos
                    LimpiarTabla(model);
            if (result.next()) {
    
                  // El registro con el ID especificado se encontró en la base de datos
                
                // Obtener los datos del resultado
                int id = result.getInt("ID_Equipo");
                String nombre = result.getString("Nombre_Equipo");
                String descripcion = result.getString("Descripcion");
               
             

                // Agregar los datos al DefaultTableModel asociado al JTable
               
                model.addRow(new Object[]{id, nombre, descripcion});
                
            jTextField6.setText(nombre);
          
            jTextArea2.setText(descripcion);
            

            } else {
                JOptionPane.showMessageDialog(null, "No se encontró un registro con el ID especificado.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al realizar la consulta en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }     
    }//GEN-LAST:event_jButton11MousePressed

    private void jButton12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MousePressed
        // TODO add your handling code here:
        boolean error = false;
        
         String nombre = jTextField6.getText().trim();
        if (!nombre.matches("^[a-zA-Z]+$")) {
            JOptionPane.showMessageDialog(null, "Error: El nombre solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        } else {
            a.setNuevoNombreEquipo(nombre);
        }

       
        a.setNuevaDescripcion(jTextArea2.getText().trim());
        
       try {
    String query = "UPDATE equipos SET Nombre_Equipo=?, Descripcion=? WHERE ID_Equipo=?";
    try (PreparedStatement pps = conSQL.prepareStatement(query)) {
        pps.setString(1, a.getNuevoNombreEquipo());
        pps.setString(2, a.getNuevaDescripcion());
        pps.setInt(3, a.getIdBuscadaEquipo());
  
        int rowsUpdated = pps.executeUpdate();
        if (rowsUpdated > 0) {
            // Suponiendo que 'm' es una instancia de la clase que muestra los datos
            JOptionPane.showMessageDialog(null, "Datos modificados correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún registro con el ID: " + a.getIdBuscada());
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error al modificar los datos en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} finally {
    // Cerrar la conexión aquí si es necesario
}

DefaultTableModel modeloTabla = (DefaultTableModel) jTable4.getModel();
LimpiarTabla(modeloTabla);
TablaModificar();
        
TablaMostrar();
TablaBuscar();
TablaModificar();
    }//GEN-LAST:event_jButton12MousePressed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
           Equipamiento equiframe = new Equipamiento();
        equiframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        Partida partidaframe = new Partida();
        partidaframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4MousePressed

    
    private void eliminarRegistro(int id) {
    try {
        // Realizar una consulta SQL para eliminar el registro con el ID especificado
        String deleteQuery = "DELETE FROM equipos WHERE ID_Equipo = ?";
        PreparedStatement deleteStatement = conSQL.prepareStatement(deleteQuery);
        deleteStatement.setInt(1, id);

        int rowsAffected = deleteStatement.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Registro eliminado con éxito.");
           TablaEliminar();
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró un registro con el ID especificado.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar el registro en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    } 
    
    private boolean idEquipoExiste(int idEquipo) {
    try {
        String query = "SELECT * FROM equipos WHERE ID_Equipo = ?";
        PreparedStatement pps = conSQL.prepareStatement(query);
        pps.setInt(1, idEquipo);

        ResultSet rs = pps.executeQuery();

        return rs.next();  // Devuelve true si hay un resultado, lo que significa que el ID de usuario ya existe
    } catch (SQLException e) {
        e.printStackTrace();
        return false;  // Manejar la excepción de alguna manera adecuada para tu aplicación
    }
}
    
    private void LimpiarTabla(DefaultTableModel model) {
    int rowCount = model.getRowCount();
    for (int i = rowCount - 1; i >= 0; i--) {
        model.removeRow(i);
    }
}
    
    
    void TablaMostrar() {
      
   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      
   String query = "SELECT * FROM equipos"; // Reemplaza esto con tu consulta SQL real

    // Llamada al método para mostrar datos en jTable2
    mostrarDatosEnTabla(jTable1, model, query);
}
    
    
    void TablaBuscar() {
      
   DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
      
   String query = "SELECT * FROM equipos"; // Reemplaza esto con tu consulta SQL real

    // Llamada al método para mostrar datos en jTable2
    mostrarDatosEnTabla(jTable2, model, query);
}
    
    void TablaEliminar() {
      
   DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
      
   String query = "SELECT * FROM equipos"; // Reemplaza esto con tu consulta SQL real

    // Llamada al método para mostrar datos en jTable2
    mostrarDatosEnTabla(jTable3, model, query);
}
    
     void TablaModificar() {
      
   DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
      
   String query = "SELECT * FROM equipos"; // Reemplaza esto con tu consulta SQL real

    // Llamada al método para mostrar datos en jTable2
    mostrarDatosEnTabla(jTable4, model, query);
}
    
    private void mostrarDatosEnTabla(JTable tabla, DefaultTableModel modelo, String consultaSQL) {
    LimpiarTabla(modelo);

    try (Connection conSQL = new ConexionDB().getConectarDB();
         Statement stmt = conSQL.createStatement();
         ResultSet result = stmt.executeQuery(consultaSQL)) {

        while (result.next()) {
            int id = result.getInt("ID_Equipo");
            String nombre = result.getString("Nombre_Equipo"); 
            String descripcion = result.getString("Descripcion");
           

            modelo.addRow(new Object[]{id, nombre, descripcion});
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al leer los datos desde la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    private void configurarSeleccionDeFilaEliminar() {
    jTable3.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = jTable3.getSelectedRow();
                if (selectedRow != -1) {
                    Object idValue = jTable3.getValueAt(selectedRow, 0); // Suponiendo que el ID está en la primera columna
                    jTextField4.setText(String.valueOf(idValue));
                }
            }
        }
    });
}
    
    private void configurarSeleccionDeFilaModificar() {
    jTable4.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = jTable4.getSelectedRow();
                if (selectedRow != -1) {
                    Object idValue = jTable4.getValueAt(selectedRow, 0); // Suponiendo que el ID está en la primera columna
                    jTextField5.setText(String.valueOf(idValue));
                }
            }
        }
    });
}
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
private final Atributos a;
}
