
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aeaya
 */
public class Partida extends javax.swing.JFrame {
ConexionDB conSQL = new ConexionDB();
    /**
     * Creates new form Partida
     */
    public Partida() {
        initComponents();
        a = new Atributos();
        
        TablaMostrar();
         TablaBuscar();
         TablaEliminar();
         TablaModificar();
         
         configurarSeleccionDeFilaEliminar();
         configurarSeleccionDeFilaModificar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton10 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel1.setText("ID PARTIDA");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 60, 110, 40);

        jLabel2.setText("FECHA DE INICIO");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 130, 150, 30);

        jLabel3.setText("HORA DE INICIO");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 190, 120, 30);

        jLabel4.setText("LUGAR");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(30, 260, 80, 30);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(140, 70, 130, 30);

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(140, 130, 140, 30);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(140, 250, 160, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA ", "LUGAR", "HORA INICIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(350, 60, 452, 402);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A.M", "P.M" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(260, 190, 60, 30);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jPanel2.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(140, 190, 110, 30);

        jButton10.setText("Guardar");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton10MousePressed(evt);
            }
        });
        jPanel2.add(jButton10);
        jButton10.setBounds(90, 390, 140, 50);

        jButton12.setText("AÑADIR EQUIPOS A PARTIDA");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton12MousePressed(evt);
            }
        });
        jPanel2.add(jButton12);
        jButton12.setBounds(150, 490, 330, 50);

        jTabbedPane1.addTab("Nueva Partida", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 153, 0));
        jPanel3.setLayout(null);

        jLabel5.setText("jLabel5");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(70, 60, 37, 16);

        jTextField3.setText("jTextField3");
        jPanel3.add(jTextField3);
        jTextField3.setBounds(160, 52, 120, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA", "LUGAR", "HORA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(60, 120, 452, 402);

        jButton6.setText("jButton6");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton6MousePressed(evt);
            }
        });
        jPanel3.add(jButton6);
        jButton6.setBounds(300, 50, 75, 23);

        jTabbedPane1.addTab("buscar", jPanel3);

        jPanel5.setBackground(new java.awt.Color(51, 153, 0));
        jPanel5.setLayout(null);

        jLabel6.setText("jLabel6");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(40, 40, 37, 16);

        jTextField4.setText("jTextField4");
        jPanel5.add(jTextField4);
        jTextField4.setBounds(120, 40, 120, 40);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA", "LUGAR", "HORA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(80, 140, 452, 402);

        jButton7.setText("jButton7");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton7MousePressed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(260, 50, 75, 23);

        jTabbedPane1.addTab("eliminar", jPanel5);

        jPanel4.setBackground(new java.awt.Color(51, 153, 0));
        jPanel4.setLayout(null);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FECHA", "LUGAR", "HORA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(40, 170, 452, 402);

        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(70, 70, 37, 16);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(160, 62, 150, 50);

        jButton8.setText("jButton8");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton8MousePressed(evt);
            }
        });
        jPanel4.add(jButton8);
        jButton8.setBounds(350, 70, 100, 50);

        jLabel8.setText("FECHA");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(540, 130, 37, 16);

        jLabel9.setText("HORA");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(540, 210, 33, 16);

        jLabel10.setText("LUGAR");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(540, 300, 37, 16);

        jDateChooser2.setDateFormatString("yyyy-MM-dd");
        jPanel4.add(jDateChooser2);
        jDateChooser2.setBounds(600, 120, 190, 40);

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));
        jPanel4.add(jFormattedTextField2);
        jFormattedTextField2.setBounds(590, 192, 140, 50);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A.M", "P.M" }));
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(740, 192, 80, 50);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(590, 280, 180, 50);

        jButton9.setText("jButton9");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton9MousePressed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(600, 420, 130, 50);

        jButton11.setText("Actualizar Tabla");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton11MousePressed(evt);
            }
        });
        jPanel4.add(jButton11);
        jButton11.setBounds(101, 130, 160, 23);

        jTabbedPane1.addTab("modificar", jPanel4);

        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(170, 30, 840, 640);

        jButton1.setText("Usuarios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 170, 120, 40);

        jButton2.setText("Equipos");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 240, 120, 40);

        jButton3.setText("Partida");
        jPanel1.add(jButton3);
        jButton3.setBounds(20, 310, 120, 40);

        jButton4.setText("Equipamiento");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(20, 380, 120, 40);

        jButton5.setText("salir");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(30, 550, 100, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1010, 670);

        setSize(new java.awt.Dimension(1020, 674));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jPanel2MousePressed

    private void jButton10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MousePressed
        // TODO add your handling code here:
         boolean error = false;

        try {
            int nuevoIdPartida = Integer.parseInt(jTextField1.getText().trim());
 
            // Verificar si el ID de usuario ya existe
            if (idPartidaExiste(nuevoIdPartida)) {
                JOptionPane.showMessageDialog(null, "Error: El ID de partida ya existe en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            a.setIdPartida(nuevoIdPartida);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Ingresa un valor numérico válido para el ID de usuario.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        }
        
        Date fechaInicio = jDateChooser1.getDate();

        // Validación de la fecha
        if (fechaInicio == null) {
            JOptionPane.showMessageDialog(null, "Error: La fecha de inicio no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        } else {
            a.setFechaInicio(fechaInicio);
        }
        
        
        
                    String horaInicioTexto = jFormattedTextField1.getText().trim();
            String abreviaturaSeleccionada = (String) jComboBox1.getSelectedItem();

            // Validación de la hora
            if (horaInicioTexto.isEmpty() || abreviaturaSeleccionada == null) {
                JOptionPane.showMessageDialog(null, "Error: La hora de inicio o la abreviatura no pueden estar vacías.", "Error", JOptionPane.ERROR_MESSAGE);
                error = true;
            } else {
                // Puedes agregar más validaciones según tus necesidades, por ejemplo, si el formato de la hora es correcto

                // Combinar la hora y la abreviatura
                String horaCompleta = horaInicioTexto + " " + abreviaturaSeleccionada;

                // Asignar la hora completa a 'a.horainicio'
                a.setHora(horaCompleta);
            }
            
            String lugar = jTextField2.getText().trim();
        if (!lugar.matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(null, "Error: El lugar solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        } else {
            a.setLugar(lugar);
        }
        
        
         try {
            String query = "INSERT INTO partida(ID_Partida, Fecha_Inicio, Lugar, Hora_Inicio) VALUES(?, ?, ?, ?)";
            PreparedStatement pps = conSQL.prepareStatement(query);
            pps.setInt(1, a.getIdPartida());
            java.sql.Date fechaSQL = new java.sql.Date(a.getFechaInicio().getTime());
            pps.setDate(2, fechaSQL);
            pps.setString(3, a.getLugar());
            pps.setString(4, a.getHora());
            

            pps.executeUpdate();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar los datos en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (!error) {
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente.");
        }
        
        TablaEliminar();
        TablaMostrar();
        TablaBuscar();
        TablaModificar();
        
        
    }//GEN-LAST:event_jButton10MousePressed

    private void jButton6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MousePressed
        // TODO add your handling code here:
        
        
          int idBuscada = 0;  // Inicializar la variable idBuscada fuera del try-catch

try {
    idBuscada = Integer.parseInt(jTextField3.getText());  // Obtener el ID de búsqueda del JTextField
} catch (NumberFormatException ex) {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese un ID válido.", "Error", JOptionPane.ERROR_MESSAGE);
    return;  // Salir del método si el usuario no ingresó un número válido
}
try {
    String query = "SELECT * FROM partida WHERE ID_Partida LIKE ?";
    PreparedStatement pstmt = conSQL.getConectarDB().prepareStatement(query);
    pstmt.setString(1, idBuscada + "%");  // El símbolo '%' permite buscar registros que comiencen con el ID proporcionado
    
    ResultSet result = pstmt.executeQuery();
    
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("FECHA");
    modelo.addColumn("LUGAR");
    modelo.addColumn("HORA");
    
    
    while (result.next()) {
        Object[] fila = new Object[9];
        fila[0] = result.getString("ID_Partida");
        fila[1] = result.getString("Fecha_Inicio");
        fila[2] = result.getString("Lugar");
        fila[3] = result.getString("Hora_Inicio");
     
       
        modelo.addRow(fila);
    }
    
    jTable2.setModel(modelo);
    
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error al buscar registros en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
}   
    }//GEN-LAST:event_jButton6MousePressed

    private void jButton7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MousePressed
        // TODO add your handling code here:
        
          // TODO add your handling code here:
        int idBuscada = 0;
    boolean entradaValida = false;

    do {
         try {
            String input = jTextField4.getText().trim();
            for (char c : input.toCharArray()) {
                if (!Character.isDigit(c)) {
                    throw new NumberFormatException();
                }
            }
            if (input.length() < 5) {
                idBuscada = Integer.parseInt(input);
               
                entradaValida = true;
            } else {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese exactamente 4 dígitos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
            break;
        }
    } while (!entradaValida);

     if (entradaValida) {
        try {
            // Realizar una consulta SQL para obtener los datos del registro en la base de datos
            String query = "SELECT * FROM partida WHERE ID_Partida = ?";
            try (PreparedStatement preparedStatement = conSQL.prepareStatement(query)) {
                preparedStatement.setInt(1, idBuscada);
                try (ResultSet result = preparedStatement.executeQuery()) {

                    DefaultTableModel model = (DefaultTableModel) jTable3.getModel();

                    // Limpiar la tabla antes de agregar nuevos datos
                    LimpiarTabla(model);

                    if (result.next()) {
                        // Obtener los datos del resultado
                        int id = result.getInt("ID_Partida");
                        String fecha = result.getString("Fecha_Inicio");
                        String lugar = result.getString("Lugar");
                        String hora = result.getString("Hora_Inicio");
                        

                        // Agregar los datos al DefaultTableModel asociado al JTable
                        model.addRow(new Object[]{id, fecha, lugar, hora});

                        // Preguntar al usuario si desea eliminar el registro
                        int opcion = JOptionPane.showConfirmDialog(null, "¿Desea eliminar el registro?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

                        if (opcion == JOptionPane.YES_OPTION) {
                            // Eliminar el registro de la base de datos
                            eliminarRegistro(id);

                            // No es necesario limpiar y mostrar la tabla aquí ya que se hace después
                        } else {
                            JOptionPane.showMessageDialog(null, "Eliminación cancelada.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "No se encontró un registro con el ID especificado.");
                    }
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error al realizar la consulta en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            }

            // Limpiar y mostrar la tabla después de la eliminación
            DefaultTableModel modeloTabla = (DefaultTableModel) jTable3.getModel();
            LimpiarTabla(modeloTabla);
            TablaEliminar();
            TablaMostrar();
            TablaBuscar();
            TablaModificar();
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese exactamente 4 dígitos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }  
        
        
        
    }//GEN-LAST:event_jButton7MousePressed

    private void jButton8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MousePressed
        // TODO add your handling code here:
          int idBuscada = 0;
    boolean entradaValida = false;

    do {
         try {
            String input = jTextField5.getText().trim();
            for (char c : input.toCharArray()) {
                if (!Character.isDigit(c)) {
                    throw new NumberFormatException();
                }
            }
            if (input.length() < 5) {
                a.setIdBuscadaPartida(Integer.parseInt(input));
               
                entradaValida = true;
            } else {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese exactamente 4 dígitos numéricos.", "Error", JOptionPane.ERROR_MESSAGE);
            break;
        }
    } while (!entradaValida);

    if (entradaValida) {
        
        try {
            // Realizar una consulta SQL para obtener los datos del registro en la base de datos
            String query = "SELECT * FROM partida WHERE ID_Partida = ?";
            PreparedStatement preparedStatement = conSQL.prepareStatement(query);
            preparedStatement.setInt(1, a.getIdBuscadaPartida());
            ResultSet result = preparedStatement.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable4.getModel();

                    // Limpiar la tabla antes de agregar nuevos datos
                    LimpiarTabla(model);
            if (result.next()) {
    
                 
                int id = result.getInt("ID_Partida");
                String fecha = result.getString("Fecha_Inicio");
                String lugar = result.getString("Lugar");
                String hora = result.getString("Hora_Inicio");

                // Dividir la hora en dos partes: la hora sin AM/PM y el AM/PM
                String[] partesHora = hora.split(" ");
                String horaSinAmPm = partesHora[0];
                String amPm = partesHora[1];

                // Agregar los datos al DefaultTableModel asociado al JTable
                model.addRow(new Object[]{id, fecha, lugar, hora});

                // Mostrar la fecha en el JDateChooser
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                Date fechaDate = dateFormat.parse(fecha);
                jDateChooser2.setDate(fechaDate);

                // Mostrar la hora sin AM/PM en el JFormattedTextField
                jFormattedTextField2.setText(horaSinAmPm);

                // Mostrar el AM/PM en el JComboBox
                jComboBox2.setSelectedItem(amPm);

                jTextField6.setText(lugar);
            

            } else {
                JOptionPane.showMessageDialog(null, "No se encontró un registro con el ID especificado.");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al realizar la consulta en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }     catch (ParseException ex) {
                  Logger.getLogger(Partida.class.getName()).log(Level.SEVERE, null, ex);
              }
    }     
    }//GEN-LAST:event_jButton8MousePressed

    private void jButton9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MousePressed
        // TODO add your handling code here:
        
        boolean error= false;
        
         Date fechaInicio = jDateChooser2.getDate();

        // Validación de la fecha
        if (fechaInicio == null) {
            JOptionPane.showMessageDialog(null, "Error: La fecha de inicio no puede estar vacía.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        } else {
            a.setNuevaFecha(fechaInicio);
        }
        
        
        
                    String horaInicioTexto = jFormattedTextField2.getText().trim();
            String abreviaturaSeleccionada = (String) jComboBox2.getSelectedItem();

            // Validación de la hora
            if (horaInicioTexto.isEmpty() || abreviaturaSeleccionada == null) {
                JOptionPane.showMessageDialog(null, "Error: La hora de inicio o la abreviatura no pueden estar vacías.", "Error", JOptionPane.ERROR_MESSAGE);
                error = true;
            } else {
                // Puedes agregar más validaciones según tus necesidades, por ejemplo, si el formato de la hora es correcto

                // Combinar la hora y la abreviatura
                String horaCompleta = horaInicioTexto + " " + abreviaturaSeleccionada;

                // Asignar la hora completa a 'a.horainicio'
                a.setNuevaHora(horaCompleta);
            }
            
            String lugar = jTextField6.getText().trim();
        if (!lugar.matches("^[a-zA-Z\\s]+$")) {
            JOptionPane.showMessageDialog(null, "Error: El lugar solo puede contener letras.", "Error", JOptionPane.ERROR_MESSAGE);
            error = true;
        } else {
            a.setNuevoLugar(lugar);
        }
        
        
        try {
    String query = "UPDATE partida SET Fecha_Inicio=?, Lugar=?, Hora_Inicio=? WHERE ID_Partida=?";
    try (PreparedStatement pps = conSQL.prepareStatement(query)) {
        
         java.sql.Date fechaSQL = new java.sql.Date(a.getNuevaFecha().getTime());
            pps.setDate(1, fechaSQL);
            pps.setString(2, a.getNuevoLugar());
            pps.setString(3, a.getNuevaHora());
            
       
        pps.setInt(4, a.getIdBuscadaPartida());
  
        int rowsUpdated = pps.executeUpdate();
        if (rowsUpdated > 0) {
            // Suponiendo que 'm' es una instancia de la clase que muestra los datos
            JOptionPane.showMessageDialog(null, "Datos modificados correctamente.");
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró ningún registro con el ID: " + a.getIdBuscada());
        }
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error al modificar los datos en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
} finally {
    // Cerrar la conexión aquí si es necesario
}

DefaultTableModel modeloTabla = (DefaultTableModel) jTable4.getModel();
LimpiarTabla(modeloTabla);
TablaModificar();
        
TablaMostrar();
TablaBuscar();
TablaModificar();
        
    }//GEN-LAST:event_jButton9MousePressed

    private void jButton11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MousePressed
        // TODO add your handling code here:
        TablaModificar();
    }//GEN-LAST:event_jButton11MousePressed

    private void jButton12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MousePressed
        // TODO add your handling code here:
        PartidaEntre parframe = new PartidaEntre();
        parframe.setVisible(true);
    }//GEN-LAST:event_jButton12MousePressed

    private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
        // TODO add your handling code here:
        Equipamiento equiframe = new Equipamiento();
        equiframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4MousePressed

    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        // TODO add your handling code here:
        Usuarios usuframe = new Usuarios();
        usuframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1MousePressed

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        // TODO add your handling code here:
        Equipos equiposframe = new Equipos();
        equiposframe.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5MousePressed

    private boolean idPartidaExiste(int idPartida) {
    try {
        String query = "SELECT * FROM partida WHERE ID_Partida = ?";
        PreparedStatement pps = conSQL.prepareStatement(query);
        pps.setInt(1, idPartida);

        ResultSet rs = pps.executeQuery();

        return rs.next();  // Devuelve true si hay un resultado, lo que significa que el ID de usuario ya existe
    } catch (SQLException e) {
        e.printStackTrace();
        return false;  // Manejar la excepción de alguna manera adecuada para tu aplicación
    }
}
    
     private void LimpiarTabla(DefaultTableModel model) {
    int rowCount = model.getRowCount();
    for (int i = rowCount - 1; i >= 0; i--) {
        model.removeRow(i);
    }
}
    
    
    void TablaMostrar() {
      
   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
      
   String query = "SELECT * FROM partida"; // Reemplaza esto con tu consulta SQL real

    // Llamada al método para mostrar datos en jTable2
    mostrarDatosEnTabla(jTable1, model, query);
}
    
    
    void TablaBuscar() {
      
   DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
      
   String query = "SELECT * FROM partida"; // Reemplaza esto con tu consulta SQL real

    // Llamada al método para mostrar datos en jTable2
    mostrarDatosEnTabla(jTable2, model, query);
}
    
    void TablaEliminar() {
      
   DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
      
   String query = "SELECT * FROM partida"; // Reemplaza esto con tu consulta SQL real

    // Llamada al método para mostrar datos en jTable2
    mostrarDatosEnTabla(jTable3, model, query);
}
    
     void TablaModificar() {
      
   DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
      
   String query = "SELECT * FROM partida"; // Reemplaza esto con tu consulta SQL real

    // Llamada al método para mostrar datos en jTable2
    mostrarDatosEnTabla(jTable4, model, query);
}
    
    private void mostrarDatosEnTabla(JTable tabla, DefaultTableModel modelo, String consultaSQL) {
    LimpiarTabla(modelo);

    try (Connection conSQL = new ConexionDB().getConectarDB();
         Statement stmt = conSQL.createStatement();
         ResultSet result = stmt.executeQuery(consultaSQL)) {

        while (result.next()) {
            int id = result.getInt("ID_Partida");
            java.sql.Date fecha = result.getDate("Fecha_Inicio");
            String lugar = result.getString("Lugar");
            String hora = result.getString("Hora_Inicio");
           

            modelo.addRow(new Object[]{id, fecha, lugar, hora});
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al leer los datos desde la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    private void eliminarRegistro(int id) {
    try {
        // Realizar una consulta SQL para eliminar el registro con el ID especificado
        String deleteQuery = "DELETE FROM partida WHERE ID_Partida = ?";
        PreparedStatement deleteStatement = conSQL.prepareStatement(deleteQuery);
        deleteStatement.setInt(1, id);

        int rowsAffected = deleteStatement.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Registro eliminado con éxito.");
           TablaEliminar();
        } else {
            JOptionPane.showMessageDialog(null, "No se encontró un registro con el ID especificado.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar el registro en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    } 
    
    
    private void configurarSeleccionDeFilaEliminar() {
    jTable3.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = jTable3.getSelectedRow();
                if (selectedRow != -1) {
                    Object idValue = jTable3.getValueAt(selectedRow, 0); // Suponiendo que el ID está en la primera columna
                    jTextField4.setText(String.valueOf(idValue));
                }
            }
        }
    });
}
    
    private void configurarSeleccionDeFilaModificar() {
    jTable4.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent event) {
            if (!event.getValueIsAdjusting()) {
                int selectedRow = jTable4.getSelectedRow();
                if (selectedRow != -1) {
                    Object idValue = jTable4.getValueAt(selectedRow, 0); // Suponiendo que el ID está en la primera columna
                    jTextField5.setText(String.valueOf(idValue));
                }
            }
        }
    });
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Partida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Partida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
private final Atributos a;
}
